### ISSUE TITLE
bidding_service fails to build on aarch64 in realese 4.7.0

### ISSUE THREAD

**Issue by kolo** [privacysandbox/bidding-auction-servers#34]
The bidding_service fails to build on aarch64 in release 4.7.0 with the following error:

```
external/inference_common/sandbox/sandbox_executor.cc:155:24: error: use of undeclared identifier '__NR_arch_prctl'
  builder.AllowSyscall(__NR_arch_prctl);
```

I use the following command to build the service:

```
builders/tools/bazel-debian build --config=local_gcp --config=non_prod //services/bidding_service:server
```

**Comment by salmanmlk** [comment]
B&A doesn't currently support aarch64.

**Comment by kolo** [comment]
I see. It it confusing though, for example [this](https://github.com/privacysandbox/bidding-auction-servers/blob/68c22a0c61d8320b655328dcfe0b28c59fd69475/production/packaging/gcp/bidding_service/BUILD?plain=1#L168) tells the opposite to me. Could it be I'm misunderstanding it?

**Comment by salmanmlk** [comment]
Good eye, Dmitry! However, we don't currently support aarch64. We might officially support this arch in future though and hence the switches / selects in the builds. Thank you for your understanding.

**Comment by salmanmlk** [comment]
Documentation updated [here](https://github.com/privacysandbox/protected-auction-services-docs/pull/216/commits/d051a678792558529b2a56fd5dea29da8a1ec860).
